version: '2.27'

services:

  app:

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - allure-server

    volumes:
      - .:/app

    command: >
      allure generate allure-results --clean -o allure-results &&
      allure serve

  test_1:
    depends_on:
      - app
      - allure-server
    build:
      context: .
    volumes:
      - ./tests/test_1:/tests/test_1
    command: >
      pytest -v --alluredir=allure-results
    ports:
      - "4050:80"


  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0

    ports:
      - "4040:4040"
