version: '2.27'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - allure-server
    volumes:
      - .:/app
      - /c/Users/evgenyp/Downloads/credentials_1.json:/app/credentials_1.json
    command: >
      bash -c "pytest allure generate allure-results --clean -o allure-results && allure serve allure-results"

  test-base:
    build:
      context: .
    depends_on:
      - app
      - allure-server
    command: >
      pytest -n auto

  container-1:
    extends:
      service: test-base
    volumes:
      - ./tests/test_1:/app/tests/test_1

  container-2:
    extends:
      service: test-base
    volumes:
      - ./tests/test_2:/app/tests/test_2

  container-3:
    extends:
      service: test-base
    volumes:
      - ./tests/test_3:/app/tests/test_3

  container-4:
    extends:
      service: test-base
    volumes:
      - ./tests/test_4:/app/tests/test_4

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"
