version: '3.9'

services:

  cellenium:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    volumes:
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}
      - shared:/usr/java
      - ./allure-results:/allure-results
    ports:
      - ${CORE_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "python --version || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: '2'
    command: >
      bash -c "pytest -n ${PARALLEL} --alluredir=allure-results &&
               allure generate allure-results --clean -o allure-results &&
               allure serve"
    depends_on:
      - java
      - allure-server

  java:
    image: ibmjava:jre
    volumes:
      - shared:/bin/jre

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - ${ALLURE_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4040" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'

volumes:
  shared:
