version: '3.0'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}
    depends_on:
      - container-1
      - container-2
      - allure-server
    environment:
      - CONTAINER=1
    command: >
      bash -c "allure generate allure-results --clean -o allure-results allure serve"

  container-1:
      build:
        context: .
      volumes:
        - .:/app
      ports:
        - ${PORT}
      healthcheck:
        test: [ "CMD-SHELL", "curl -f http://localhost:${PORT} || exit 1" ]
        interval: 30s
        timeout: 10s
        retries: 5
      command: >
        bash -c "pytest tests/test_1 -n ${PARALLEL}"

  container-2:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - ${PORT}
    command: >
      bash -c "pytest tests/test_2 -n ${PARALLEL} && allure generate allure-results --clean -o allure-results" 

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"
