version: '3'

volumes:
  shared:

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - allure-server
    entrypoint: ["./environment/init_credentials.sh"]
    volumes:
      - .:/app
      - shared:/app/credentials

    command: >
      pytest -v --alluredir=allure-results 
      allure generate allure-results --clean -o allure-results &&
      allure serve

  test_1:
    build:
      context: .
    volumes:
      - ./tests/test_1:/app/tests/test_1
    depends_on:
      - app
      - allure-server
    command: >
      pytest -v --alluredir=allure-results 

  test_2:
    build:
      context: .
    volumes:
      - ./tests/test_2:/app/tests/test_2
    depends_on:
      - app
      - allure-server
    command: >
      pytest -v --alluredir=allure-results  


  allure-server:
    image: frankescobar/allure-docker-service
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0

    ports:
      - "4040:4040"
