version: '3.0'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${CREDENTIALS}:/app/environment/_json/credentials.json
    depends_on:
      - container-1
      - allure-server
    command:
      bash -c "pytest && allure generate allure-results --clean -o allure-results && allure serve"

  main_container:
    build:
      context: .

  container-1:
    build:
      context: .
    volumes:
      - ./tests:/app/tests
    command: > 
      pytest tests/test_1

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"
