version: '3.0'

services:

  cellenium:
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
        OPENAI_API_VERSION: ${OPENAI_API_VERSION}
        MODEL: ${MODEL}
    env_file:
      - /.env
    ports:
      - "8888:8888"
    networks:
      - my-network

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"

networks:
  my-network:
    driver: bridge
