version: '3.9'

services:

  cellenium:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      allure-server:
        condition: service_started
    volumes:
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}
    ports:
      - ${CORE_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "python --version || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  test_1:
    build:
      context: ./tests/test_1
    depends_on:
      allure-server:
        condition: service_started
      cellenium:
        condition: service_healthy
    ports:
      - ${TEST_PORT}
    command: >
      bash -c "pytest -n ${PARALLEL} && allure generate allure-results --clean -o allure-results && allure serve"
    healthcheck:
      test: [ "CMD-SHELL", "python --version || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"
    healthcheck:
      test: ["CMD", "allure --version"]
      interval: 10s
      retries: 6
    restart: on-failure
