version: '3.9'

services:

  cellenium:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    depends_on:
      - cellenium
    volumes:
      - ./core:/core

  tests:
      build:
        context: ./tests
      depends_on:
        - core
        - allure-server
      volumes:
        - ./tests:/tests
      ports:
        - ${PORT}
      healthcheck:
        test: [ "CMD-SHELL", "curl -f http://localhost:${PORT} || exit 1" ]
        interval: 30s
        timeout: 10s
        retries: 5
      environment:
        - DEBUG=true
      command: >
        bash -c "pytest -n ${PARALLEL} && allure generate allure-results --clean -o allure-results && allure serve"

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0
    ports:
      - "4040:4040"
