version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      allure generate allure-results --clean -o allure-results &&
      allure serve
    extends:
      service:
        api
    depends_on:
      - allure-server

  api:
    build:
      context: .
    volumes:
      - /C:/Users/evgenyp/Downloads/credentials_1.json:/app/credentials_1.json

  test_button:
    extends:
      service: app
    volumes:
      - ./tests/test_button:/app/tests/test_button
    depends_on:
      - allure-server
    command: >
      pytest -v --alluredir=allure-results ./tests/test_button

  allure-server:
    image: frankescobar/allure-docker-service
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
      ANALYTICS: 1
      SECURITY: 0

    ports:
      - "4040:4040"
