[tool.poetry]
name = "bini"
version = "0.1.0"
description = "Describe your project here"
authors = ["Jenia P"]
readme = "README.md"
packages = [{include = "your_package"}]


[tool.poetry.dependencies]
python = ">=3.10,<3.14"
fastapi = "^0.111.0"
mcp = {version = "~1.9.2", 'extras' = ['cli']}
fastmcp = "~2.6.1"
langchain-openai = "0.3.22"
crewai = "0.126.0"
google = "3.0.0"
google-api-core = "2.20.0"
google-auth = "2.29.0"
google-auth-oauthlib = "1.2.0"
pytest = "8.2.1"
python-dotenv = "~1.1.0"
selenium = "~4.28.1"
webdriver-manager = "4.0.1"
requests = "~2.32.3"
playwright = "~1.49.1"
langchain-core = "~0.3.31"
pydantic = "2.11.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
