task:
  agent: agent
  description: |
    You will navigate to web page: {url}
    You will receive a sentence: {prompt}
    Your tasks are:
      automate browser automation tasks, such as data extraction, form filling, and navigation.

  expected_output: |
    accurate automation flow
