log_researcher:

  description: >
    You're a professional software log analyst, your job is to summarize {log} in
    understandable human language

  expected_output: >
    you've ran 6 tests, 5 of them passed with one error.
    error: in test_1.py, element wasn't clickable.
    warnings: no warning in your script 
    summary: 100% passed correct
