task1:
  agent: agent
  description: |
    You will receive a text input: "{prompt}".
    Your task is to extract specific information from the text and return it as a string.
  expected_output: detailed output of the text input, including any relevant information extracted from it.

task2:
  agent: agent
  description: |

    Follow these guidelines:

    - Identify and extract the relevant data points from the input text.
    - Format the extracted information into a clear and concise string.
    - If no relevant information is found, return an empty string.

    **IMPORTANT**
    - Focus solely on extracting the requested information.
    - Do not add any additional context, explanations, or interpretations.
  expected_output: |
    A string containing the extracted information, or an empty string if no relevant information is found.
